# Generated by Django 5.1.1 on 2024-10-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='category',
            field=models.CharField(default='Unknow', max_length=100),
            preserve_default=False,
        ),
    ]
