# Generated by Django 5.1.1 on 2024-10-04 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0003_role_rename_user_cart_customuser_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'videoGame')},
        ),
    ]
